name: quangis
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - pip
  - nodejs
  - make
  - spacy
  - spacy-model-en_core_web_sm
  - antlr4-python3-runtime=4.9.3
  - nltk
  - word2number
  - django
  - checklist
  - rdflib
  - plumbum
  - pip:
    - checklist # versioning conflicts
    - allennlp # not available for windows on conda-forge
    - allennlp-models
    - "--editable=git+https://github.com/quangis/transformation-algebra.git@develop#egg=transformation-algebra"
    - "--editable=git+https://github.com/quangis/cct.git#egg=cct"
    - "--editable=git+https://github.com/quangis/geo-question-parser.git#egg=geo-question-parser"
